config/routes.rb
Rails.application.routes.draw do
  root :to => 'users#index'

  resources :sessions

  resources :users do
    resources :photos
  end

  get "/log-in" => "sessions#new"
  post "/log-in" => "sessions#create"
  get "/log-out" => "sessions#destroy", as: :log_out

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  has_and_belongs_to_many :users
  belongs_to :user
  has_attached_file :photo, styles: { medium: "300", thumb: "100x100#" }
  validates_attachment :photo, presence: true, content_type: {content_type: /\Aimage/}

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  before_save :encrypt_password
  validates :name, :email, :presence => true
  has_and_belongs_to_many :photos
  
  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(self.password, password_salt)
  end

  def self.authenticate(email, password)
    user = User.where(:email => email).first
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      return user
    else
      return nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  config.paperclip_defaults = {:storage => :fog, :fog_credentials => {:provider => "Local", :local_root => "#{Rails.root}/public"}, :fog_directory => "", :fog_host => "localhost"}
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    @photo = Photo.all.order("created_at DESC")
  end


  def new
    @user = User.find(params[:user_id])
    @photo = Photo.create()
  end

  def create
    @user = User.find(params[:user_id])
    @photo = Photo.create(photo_params)

    if @photo.save
      @user.photos << @photo
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def show

  end

  def edit
    @user = User.find(params[:user_id])
    @photo = Photo.find(params[:id])
  end

  def destroy
    @user = User.find(params[:user_id])
    @photo = Photo.find(params[:id])
    @photo.destroy
    redirect_to user_path(@user)
  end

  def update
    @user = User.find(params[:user_id])
    @photo = Photo.find(params[:id])
    @photo << @user
    if @photo.update(params[:user])
      redirect_to user_path(@photo.user)
    else
      flash[:alert] = "Did not tag user to foto. Please contact the president."
      render :edit
    end
  end


private
  def photo_params
    params.require(:photo).permit(:photo, :url, :html, :title, :user)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    if User.authenticate(params[:email], params[:password])
      @user = User.find_by(:email => params[:email])
      session[:user_id] = @user.id
      current_user = User.find(@user.id)
      flash[:notice] = "You have logged in to Foto Friends, the hot new website!"
      redirect_to "/"
    else
      flash[:alert] = "NO NO NO... NAUGHTY NAUGHTY"
      redirect_to log_in_path
    end
  end


  def destroy
    session[:user_id] = nil
    flash[:notice] = "You have been logged out... fare thee well..."
    redirect_to "/"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @name = params.fetch(:name, "default")
    @password = params.fetch(:password, "default")
    @email = params.fetch(:email, "default")
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path
    else
      render :new
    end
  end
    def show
      @user = User.find(params[:id])
      @photos = @user.photos.all
      @photo = Photo.new
    end

    def edit
      @user = User.find(params[:id])
    end

    def destroy
      @user = User.find(params[:id])
      @user.destroy
      redirect_to users_path
    end

    def update
      @user = User.find(params[:id])
      if @user.update(params[:user])
        redirect_to users_path
      else
        render :edit
      end
    end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Oops there were some errors. Please try again:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FotoFriends</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  
</head>
<body>


<font color="red"><%= flash[:alert] %></font>
<font color="green"><%= flash[:notice] %></font>

<%= yield %>

</body>
</html>

app/views/photos/_form.html.erb
<%= render "layouts/errors", :object => @photo %>

<%= form_for Photo.new, :url => user_photos_path, :html => { :multipart => true } do |form| %>
<%= form.label :title %>
<%= form.text_field :title %>
<%= form.label :photo %>
<%= form.file_field :photo %>
<%= form.submit "upload"%>
<% end %>

app/views/photos/new.html.erb
<%= render 'form' %>

app/views/photos/show.html.erb
<h1><%= @photo.title %> </h1>

<%= image_tag @photo.photo.url %>
<%= form_tag("/users_path", method: "get") do %>
<%= label_tag(:@user:) %>
<%= text_field_tag(:q) %>
<%= submit_tag("tag") %>
<% end %>

app/views/users/_form.html.erb
<%= render "layouts/errors", :object => @user %>

<%= form_for @user do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%=f.label :email %>
  <%=f.text_field :email %>
  <%=f.label :password %>
  <%=f.password_field :password %>
  <%=f.label :password_confirmation %>
  <%=f.password_field :password_confirmation %>
  <%= f.submit "Sign Up" %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit section</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 center">
      <h1>Profiles</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
        <% if current_user %>
        <p> You are logged in as <h2><%= link_to current_user[:name], user_path(current_user) %></h2> </p>
        <% end %>
        <p>  <%= link_to "log-out", log_out_path %></p>
        <p><%= link_to "Register New Account", new_user_path %>
      </p>
      <p>
        <%= link_to "Login to an Existing Account", log_in_path %>
      </p>
        <% if @users.nil? == false %>
            <% @users.each do |user| %>
            <div class="jumbotron">
              <li><%= link_to user.name, user_path(user) %></li>
              <% if user.photos.any? %>
                <%= image_tag user.photos[0].photo(:thumb) %>
              <% end %>
            </div>
          <% end %>
        <% end %>
    </div>
  </div>

app/views/users/new.html.erb
<h1>New Section</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1> <%= @user.name %> </h1>
<h2> <%= @user.email %></h2>

  <h1><%= @photo.title %> </h1>
    <% if @user.photos.any? %>
    <% @user.photos.each do |photo| %>
      <p> <%= photo.title %> </p>
      <%= image_tag photo.photo(:medium) %>
  <% end %>
  <% end %>

<% if current_user %>

  <% if current_user.id == @user.id %>

    <p><%= link_to "Delete My Account", user_path(@user),
    :data => {:confirm => "Are you sure???", :method => "delete"} %></p>
    <%= link_to "Upload a photo", new_user_photo_path(@user) %>

  <% end %>
    <p><%= link_to "Return to Feed", users_path %></p>

<% end %>